# Generated by Django 4.2.1 on 2023-05-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_category_name_category_name_shirt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
