# Generated by Django 4.2.1 on 2023-05-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
