# Generated by Django 4.2.1 on 2023-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
