# Generated by Django 4.2.1 on 2023-06-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_id',
            new_name='uid',
        ),
    ]
